; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:main]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_extra_dirs = 
	CAN-Library/MART_CAN/lib
#upload_speed = 115200
monitor_speed = 115200
build_src_filter = +<*.*> -<hall.cpp> 
build_flags =
    -DCONFIG_ESP32_ENABLE_COREDUMP=y
    -DCONFIG_ESP32_ENABLE_COREDUMP_TO_FLASH=y
    -DCONFIG_ESP32_COREDUMP_DATA_FORMAT_ELF=y
	-D CONFIG_ESP_SYSTEM_PANIC_PRINT_REBOOT=y
build_type = debug



monitor_filters = esp32_exception_decoder
#board_build.tasks.loop.stack_size = 1000

; --- DEBUGGING SETTINGS ---
debug_tool = esp-builtin
debug_build_flags = -Og -g -ggdb -DCORE_DEBUG_LEVEL=5

