; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:main]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_extra_dirs = 
	CAN-Library/MART_CAN/lib
#upload_speed = 115200
monitor_speed = 115200
build_src_filter = +<*.*> -<hall.cpp> 
build_flags = ${env.build_flags}
monitor_filters = esp32_exception_decoder
#board_build.tasks.loop.stack_size = 8192

[env:hall]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter = +<*.*> -<main.cpp> 
build_flags = ${env.build_flags}